language: node_js
install:
- yarn install --frozen-lockfile
script:
- yarn type-check
- yarn type-coverage --strict --detail
- yarn lint
deploy:
  provider: npm
  email: "joel.pearson@gmail.com"
  on:
    tags: true
  api_key:
      secure: iQBVk+943napwJs6YAuEse+Mn43Jmg7k6yhS6SeD56ePUEBV1/WwxsQ3mlcsStaXgFsIIC6ckh+8k4FzIJysJadjAuwJV3ON29QrXnV3STX79MZlMpdGemNba5/VuhEYRmzn8iHDcHZLWv2LmoLYRqcE+zXvYsLJPPX+YPV1fe6dEHFql9e9UPKkQMB1fle+lRoM7/ycDT5B/1xZGUQoHnovdD6d0XQEkebOwb8xrjSHKIZpEsXPySxbTIqV6f2l8hvNv15rti8f6NGEMRSU6FYnifhTuxrGnCJ5uoEoZlye0OE9CH8gs5LDzIO2HBw59bX5cCnfZOVZAaGKclQgBrKenRqsb0WBd2ZOanNAaOXgw/3jdmzJybUQrTAmNTwxwXeJ2CaVBMU96+3WeiwiUzugEu2hghwyBuU0FYjivZRHpJkzx4evEZsaVAnMmHeBuN9CqE+HmfWd8nfWJyMhR6t9ueyxI+hWjywLthEbmB2pU2M5RXeGzz1B4fAMXCPq7QzTffpPFC5MntwCo0/oHQh0S7DvHGRHIj4VB2tsw8SfPVxfaEH8NKlGuiUpT7MKZu7BFcgzhIT7zwLw1J4/GCyYEAmDKO/YtC5pJUQCpzhHKwFcvn7dB7HKeHMwzzwH6Swot1g2aYQ0YVgenDgWqN556mcMzYWn2gm/glHdZJI=
